// Code generated by mockery v2.42.3. DO NOT EDIT.

package ethereum

import (
	json "encoding/json"

	mock "github.com/stretchr/testify/mock"
)

// MockResponseParserFunc is an autogenerated mock type for the ResponseParserFunc type
type MockResponseParserFunc[T interface{}] struct {
	mock.Mock
}

// Execute provides a mock function with given fields: res
func (_m *MockResponseParserFunc[T]) Execute(res json.RawMessage) (T, error) {
	ret := _m.Called(res)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 T
	var r1 error
	if rf, ok := ret.Get(0).(func(json.RawMessage) (T, error)); ok {
		return rf(res)
	}
	if rf, ok := ret.Get(0).(func(json.RawMessage) T); ok {
		r0 = rf(res)
	} else {
		r0 = ret.Get(0).(T)
	}

	if rf, ok := ret.Get(1).(func(json.RawMessage) error); ok {
		r1 = rf(res)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockResponseParserFunc creates a new instance of MockResponseParserFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockResponseParserFunc[T interface{}](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockResponseParserFunc[T] {
	mock := &MockResponseParserFunc[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
