// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package blockchain

import (
	"context"
	"math/big"

	"github.com/ethereum/go-ethereum"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/core/types"
	mock "github.com/stretchr/testify/mock"
)

// NewMockEVMClient creates a new instance of MockEVMClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEVMClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEVMClient {
	mock := &MockEVMClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEVMClient is an autogenerated mock type for the EVMClient type
type MockEVMClient struct {
	mock.Mock
}

type MockEVMClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEVMClient) EXPECT() *MockEVMClient_Expecter {
	return &MockEVMClient_Expecter{mock: &_m.Mock}
}

// BalanceAt provides a mock function for the type MockEVMClient
func (_mock *MockEVMClient) BalanceAt(ctx context.Context, account common.Address, blockNumber *big.Int) (*big.Int, error) {
	ret := _mock.Called(ctx, account, blockNumber)

	if len(ret) == 0 {
		panic("no return value specified for BalanceAt")
	}

	var r0 *big.Int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, common.Address, *big.Int) (*big.Int, error)); ok {
		return returnFunc(ctx, account, blockNumber)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, common.Address, *big.Int) *big.Int); ok {
		r0 = returnFunc(ctx, account, blockNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*big.Int)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, common.Address, *big.Int) error); ok {
		r1 = returnFunc(ctx, account, blockNumber)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEVMClient_BalanceAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BalanceAt'
type MockEVMClient_BalanceAt_Call struct {
	*mock.Call
}

// BalanceAt is a helper method to define mock.On call
//   - ctx context.Context
//   - account common.Address
//   - blockNumber *big.Int
func (_e *MockEVMClient_Expecter) BalanceAt(ctx interface{}, account interface{}, blockNumber interface{}) *MockEVMClient_BalanceAt_Call {
	return &MockEVMClient_BalanceAt_Call{Call: _e.mock.On("BalanceAt", ctx, account, blockNumber)}
}

func (_c *MockEVMClient_BalanceAt_Call) Run(run func(ctx context.Context, account common.Address, blockNumber *big.Int)) *MockEVMClient_BalanceAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 common.Address
		if args[1] != nil {
			arg1 = args[1].(common.Address)
		}
		var arg2 *big.Int
		if args[2] != nil {
			arg2 = args[2].(*big.Int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEVMClient_BalanceAt_Call) Return(intParam *big.Int, err error) *MockEVMClient_BalanceAt_Call {
	_c.Call.Return(intParam, err)
	return _c
}

func (_c *MockEVMClient_BalanceAt_Call) RunAndReturn(run func(ctx context.Context, account common.Address, blockNumber *big.Int) (*big.Int, error)) *MockEVMClient_BalanceAt_Call {
	_c.Call.Return(run)
	return _c
}

// BlockNumber provides a mock function for the type MockEVMClient
func (_mock *MockEVMClient) BlockNumber(ctx context.Context) (uint64, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for BlockNumber")
	}

	var r0 uint64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (uint64, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) uint64); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(uint64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEVMClient_BlockNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BlockNumber'
type MockEVMClient_BlockNumber_Call struct {
	*mock.Call
}

// BlockNumber is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockEVMClient_Expecter) BlockNumber(ctx interface{}) *MockEVMClient_BlockNumber_Call {
	return &MockEVMClient_BlockNumber_Call{Call: _e.mock.On("BlockNumber", ctx)}
}

func (_c *MockEVMClient_BlockNumber_Call) Run(run func(ctx context.Context)) *MockEVMClient_BlockNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEVMClient_BlockNumber_Call) Return(v uint64, err error) *MockEVMClient_BlockNumber_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockEVMClient_BlockNumber_Call) RunAndReturn(run func(ctx context.Context) (uint64, error)) *MockEVMClient_BlockNumber_Call {
	_c.Call.Return(run)
	return _c
}

// CallContract provides a mock function for the type MockEVMClient
func (_mock *MockEVMClient) CallContract(ctx context.Context, call ethereum.CallMsg, blockNumber *big.Int) ([]byte, error) {
	ret := _mock.Called(ctx, call, blockNumber)

	if len(ret) == 0 {
		panic("no return value specified for CallContract")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ethereum.CallMsg, *big.Int) ([]byte, error)); ok {
		return returnFunc(ctx, call, blockNumber)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ethereum.CallMsg, *big.Int) []byte); ok {
		r0 = returnFunc(ctx, call, blockNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ethereum.CallMsg, *big.Int) error); ok {
		r1 = returnFunc(ctx, call, blockNumber)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEVMClient_CallContract_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CallContract'
type MockEVMClient_CallContract_Call struct {
	*mock.Call
}

// CallContract is a helper method to define mock.On call
//   - ctx context.Context
//   - call ethereum.CallMsg
//   - blockNumber *big.Int
func (_e *MockEVMClient_Expecter) CallContract(ctx interface{}, call interface{}, blockNumber interface{}) *MockEVMClient_CallContract_Call {
	return &MockEVMClient_CallContract_Call{Call: _e.mock.On("CallContract", ctx, call, blockNumber)}
}

func (_c *MockEVMClient_CallContract_Call) Run(run func(ctx context.Context, call ethereum.CallMsg, blockNumber *big.Int)) *MockEVMClient_CallContract_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ethereum.CallMsg
		if args[1] != nil {
			arg1 = args[1].(ethereum.CallMsg)
		}
		var arg2 *big.Int
		if args[2] != nil {
			arg2 = args[2].(*big.Int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEVMClient_CallContract_Call) Return(bytes []byte, err error) *MockEVMClient_CallContract_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockEVMClient_CallContract_Call) RunAndReturn(run func(ctx context.Context, call ethereum.CallMsg, blockNumber *big.Int) ([]byte, error)) *MockEVMClient_CallContract_Call {
	_c.Call.Return(run)
	return _c
}

// ChainID provides a mock function for the type MockEVMClient
func (_mock *MockEVMClient) ChainID(ctx context.Context) (*big.Int, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ChainID")
	}

	var r0 *big.Int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*big.Int, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *big.Int); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*big.Int)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEVMClient_ChainID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChainID'
type MockEVMClient_ChainID_Call struct {
	*mock.Call
}

// ChainID is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockEVMClient_Expecter) ChainID(ctx interface{}) *MockEVMClient_ChainID_Call {
	return &MockEVMClient_ChainID_Call{Call: _e.mock.On("ChainID", ctx)}
}

func (_c *MockEVMClient_ChainID_Call) Run(run func(ctx context.Context)) *MockEVMClient_ChainID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEVMClient_ChainID_Call) Return(intParam *big.Int, err error) *MockEVMClient_ChainID_Call {
	_c.Call.Return(intParam, err)
	return _c
}

func (_c *MockEVMClient_ChainID_Call) RunAndReturn(run func(ctx context.Context) (*big.Int, error)) *MockEVMClient_ChainID_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type MockEVMClient
func (_mock *MockEVMClient) Close() {
	_mock.Called()
	return
}

// MockEVMClient_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockEVMClient_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockEVMClient_Expecter) Close() *MockEVMClient_Close_Call {
	return &MockEVMClient_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockEVMClient_Close_Call) Run(run func()) *MockEVMClient_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEVMClient_Close_Call) Return() *MockEVMClient_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEVMClient_Close_Call) RunAndReturn(run func()) *MockEVMClient_Close_Call {
	_c.Run(run)
	return _c
}

// EstimateGas provides a mock function for the type MockEVMClient
func (_mock *MockEVMClient) EstimateGas(ctx context.Context, call ethereum.CallMsg) (uint64, error) {
	ret := _mock.Called(ctx, call)

	if len(ret) == 0 {
		panic("no return value specified for EstimateGas")
	}

	var r0 uint64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ethereum.CallMsg) (uint64, error)); ok {
		return returnFunc(ctx, call)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ethereum.CallMsg) uint64); ok {
		r0 = returnFunc(ctx, call)
	} else {
		r0 = ret.Get(0).(uint64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ethereum.CallMsg) error); ok {
		r1 = returnFunc(ctx, call)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEVMClient_EstimateGas_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EstimateGas'
type MockEVMClient_EstimateGas_Call struct {
	*mock.Call
}

// EstimateGas is a helper method to define mock.On call
//   - ctx context.Context
//   - call ethereum.CallMsg
func (_e *MockEVMClient_Expecter) EstimateGas(ctx interface{}, call interface{}) *MockEVMClient_EstimateGas_Call {
	return &MockEVMClient_EstimateGas_Call{Call: _e.mock.On("EstimateGas", ctx, call)}
}

func (_c *MockEVMClient_EstimateGas_Call) Run(run func(ctx context.Context, call ethereum.CallMsg)) *MockEVMClient_EstimateGas_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ethereum.CallMsg
		if args[1] != nil {
			arg1 = args[1].(ethereum.CallMsg)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEVMClient_EstimateGas_Call) Return(v uint64, err error) *MockEVMClient_EstimateGas_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockEVMClient_EstimateGas_Call) RunAndReturn(run func(ctx context.Context, call ethereum.CallMsg) (uint64, error)) *MockEVMClient_EstimateGas_Call {
	_c.Call.Return(run)
	return _c
}

// PendingNonceAt provides a mock function for the type MockEVMClient
func (_mock *MockEVMClient) PendingNonceAt(ctx context.Context, account common.Address) (uint64, error) {
	ret := _mock.Called(ctx, account)

	if len(ret) == 0 {
		panic("no return value specified for PendingNonceAt")
	}

	var r0 uint64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, common.Address) (uint64, error)); ok {
		return returnFunc(ctx, account)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, common.Address) uint64); ok {
		r0 = returnFunc(ctx, account)
	} else {
		r0 = ret.Get(0).(uint64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, common.Address) error); ok {
		r1 = returnFunc(ctx, account)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEVMClient_PendingNonceAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PendingNonceAt'
type MockEVMClient_PendingNonceAt_Call struct {
	*mock.Call
}

// PendingNonceAt is a helper method to define mock.On call
//   - ctx context.Context
//   - account common.Address
func (_e *MockEVMClient_Expecter) PendingNonceAt(ctx interface{}, account interface{}) *MockEVMClient_PendingNonceAt_Call {
	return &MockEVMClient_PendingNonceAt_Call{Call: _e.mock.On("PendingNonceAt", ctx, account)}
}

func (_c *MockEVMClient_PendingNonceAt_Call) Run(run func(ctx context.Context, account common.Address)) *MockEVMClient_PendingNonceAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 common.Address
		if args[1] != nil {
			arg1 = args[1].(common.Address)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEVMClient_PendingNonceAt_Call) Return(v uint64, err error) *MockEVMClient_PendingNonceAt_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockEVMClient_PendingNonceAt_Call) RunAndReturn(run func(ctx context.Context, account common.Address) (uint64, error)) *MockEVMClient_PendingNonceAt_Call {
	_c.Call.Return(run)
	return _c
}

// SendTransaction provides a mock function for the type MockEVMClient
func (_mock *MockEVMClient) SendTransaction(ctx context.Context, tx *types.Transaction) error {
	ret := _mock.Called(ctx, tx)

	if len(ret) == 0 {
		panic("no return value specified for SendTransaction")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.Transaction) error); ok {
		r0 = returnFunc(ctx, tx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEVMClient_SendTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendTransaction'
type MockEVMClient_SendTransaction_Call struct {
	*mock.Call
}

// SendTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *types.Transaction
func (_e *MockEVMClient_Expecter) SendTransaction(ctx interface{}, tx interface{}) *MockEVMClient_SendTransaction_Call {
	return &MockEVMClient_SendTransaction_Call{Call: _e.mock.On("SendTransaction", ctx, tx)}
}

func (_c *MockEVMClient_SendTransaction_Call) Run(run func(ctx context.Context, tx *types.Transaction)) *MockEVMClient_SendTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *types.Transaction
		if args[1] != nil {
			arg1 = args[1].(*types.Transaction)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEVMClient_SendTransaction_Call) Return(err error) *MockEVMClient_SendTransaction_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEVMClient_SendTransaction_Call) RunAndReturn(run func(ctx context.Context, tx *types.Transaction) error) *MockEVMClient_SendTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// SuggestGasPrice provides a mock function for the type MockEVMClient
func (_mock *MockEVMClient) SuggestGasPrice(ctx context.Context) (*big.Int, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for SuggestGasPrice")
	}

	var r0 *big.Int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*big.Int, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *big.Int); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*big.Int)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEVMClient_SuggestGasPrice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SuggestGasPrice'
type MockEVMClient_SuggestGasPrice_Call struct {
	*mock.Call
}

// SuggestGasPrice is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockEVMClient_Expecter) SuggestGasPrice(ctx interface{}) *MockEVMClient_SuggestGasPrice_Call {
	return &MockEVMClient_SuggestGasPrice_Call{Call: _e.mock.On("SuggestGasPrice", ctx)}
}

func (_c *MockEVMClient_SuggestGasPrice_Call) Run(run func(ctx context.Context)) *MockEVMClient_SuggestGasPrice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEVMClient_SuggestGasPrice_Call) Return(intParam *big.Int, err error) *MockEVMClient_SuggestGasPrice_Call {
	_c.Call.Return(intParam, err)
	return _c
}

func (_c *MockEVMClient_SuggestGasPrice_Call) RunAndReturn(run func(ctx context.Context) (*big.Int, error)) *MockEVMClient_SuggestGasPrice_Call {
	_c.Call.Return(run)
	return _c
}

// TransactionReceipt provides a mock function for the type MockEVMClient
func (_mock *MockEVMClient) TransactionReceipt(ctx context.Context, txHash common.Hash) (*types.Receipt, error) {
	ret := _mock.Called(ctx, txHash)

	if len(ret) == 0 {
		panic("no return value specified for TransactionReceipt")
	}

	var r0 *types.Receipt
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, common.Hash) (*types.Receipt, error)); ok {
		return returnFunc(ctx, txHash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, common.Hash) *types.Receipt); ok {
		r0 = returnFunc(ctx, txHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Receipt)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, common.Hash) error); ok {
		r1 = returnFunc(ctx, txHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEVMClient_TransactionReceipt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TransactionReceipt'
type MockEVMClient_TransactionReceipt_Call struct {
	*mock.Call
}

// TransactionReceipt is a helper method to define mock.On call
//   - ctx context.Context
//   - txHash common.Hash
func (_e *MockEVMClient_Expecter) TransactionReceipt(ctx interface{}, txHash interface{}) *MockEVMClient_TransactionReceipt_Call {
	return &MockEVMClient_TransactionReceipt_Call{Call: _e.mock.On("TransactionReceipt", ctx, txHash)}
}

func (_c *MockEVMClient_TransactionReceipt_Call) Run(run func(ctx context.Context, txHash common.Hash)) *MockEVMClient_TransactionReceipt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 common.Hash
		if args[1] != nil {
			arg1 = args[1].(common.Hash)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEVMClient_TransactionReceipt_Call) Return(receipt *types.Receipt, err error) *MockEVMClient_TransactionReceipt_Call {
	_c.Call.Return(receipt, err)
	return _c
}

func (_c *MockEVMClient_TransactionReceipt_Call) RunAndReturn(run func(ctx context.Context, txHash common.Hash) (*types.Receipt, error)) *MockEVMClient_TransactionReceipt_Call {
	_c.Call.Return(run)
	return _c
}
