// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	"context"
	"math/big"

	"github.com/ethereum/go-ethereum"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/core/types"
	"github.com/stretchr/testify/mock"
)

// MockEVMClient is a mock implementation of blockchain.EVMClient
type MockEVMClient struct {
	mock.Mock
}

// NewMockEVMClient creates a new MockEVMClient
func NewMockEVMClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEVMClient {
	m := &MockEVMClient{}
	m.Mock.Test(t)
	t.Cleanup(func() { m.AssertExpectations(t) })
	return m
}

// BalanceAt implements blockchain.EVMClient.BalanceAt
func (m *MockEVMClient) BalanceAt(ctx context.Context, account common.Address, blockNumber *big.Int) (*big.Int, error) {
	args := m.Called(ctx, account, blockNumber)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*big.Int), args.Error(1)
}

// CallContract implements blockchain.EVMClient.CallContract
func (m *MockEVMClient) CallContract(ctx context.Context, call ethereum.CallMsg, blockNumber *big.Int) ([]byte, error) {
	args := m.Called(ctx, call, blockNumber)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).([]byte), args.Error(1)
}

// SendTransaction implements blockchain.EVMClient.SendTransaction
func (m *MockEVMClient) SendTransaction(ctx context.Context, tx *types.Transaction) error {
	args := m.Called(ctx, tx)
	return args.Error(0)
}

// TransactionReceipt implements blockchain.EVMClient.TransactionReceipt
func (m *MockEVMClient) TransactionReceipt(ctx context.Context, txHash common.Hash) (*types.Receipt, error) {
	args := m.Called(ctx, txHash)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*types.Receipt), args.Error(1)
}

// ChainID implements blockchain.EVMClient.ChainID
func (m *MockEVMClient) ChainID(ctx context.Context) (*big.Int, error) {
	args := m.Called(ctx)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*big.Int), args.Error(1)
}

// BlockNumber implements blockchain.EVMClient.BlockNumber
func (m *MockEVMClient) BlockNumber(ctx context.Context) (uint64, error) {
	args := m.Called(ctx)
	return args.Get(0).(uint64), args.Error(1)
}

// PendingNonceAt implements blockchain.EVMClient.PendingNonceAt
func (m *MockEVMClient) PendingNonceAt(ctx context.Context, account common.Address) (uint64, error) {
	args := m.Called(ctx, account)
	return args.Get(0).(uint64), args.Error(1)
}

// EstimateGas implements blockchain.EVMClient.EstimateGas
func (m *MockEVMClient) EstimateGas(ctx context.Context, call ethereum.CallMsg) (uint64, error) {
	args := m.Called(ctx, call)
	return args.Get(0).(uint64), args.Error(1)
}

// SuggestGasPrice implements blockchain.EVMClient.SuggestGasPrice
func (m *MockEVMClient) SuggestGasPrice(ctx context.Context) (*big.Int, error) {
	args := m.Called(ctx)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*big.Int), args.Error(1)
}

// Close implements blockchain.EVMClient.Close
func (m *MockEVMClient) Close() {
	m.Called()
}

// EXPECT returns an expecter for the mock
func (m *MockEVMClient) EXPECT() *MockEVMClientExpectations {
	return &MockEVMClientExpectations{mock: &m.Mock}
}

// MockEVMClientExpectations provides expectation helpers
type MockEVMClientExpectations struct {
	mock *mock.Mock
}

// BalanceAt expectation helper
func (e *MockEVMClientExpectations) BalanceAt(ctx interface{}, account interface{}, blockNumber interface{}) *mock.Call {
	return e.mock.On("BalanceAt", ctx, account, blockNumber)
}

// CallContract expectation helper
func (e *MockEVMClientExpectations) CallContract(ctx interface{}, call interface{}, blockNumber interface{}) *mock.Call {
	return e.mock.On("CallContract", ctx, call, blockNumber)
}

// SendTransaction expectation helper
func (e *MockEVMClientExpectations) SendTransaction(ctx interface{}, tx interface{}) *mock.Call {
	return e.mock.On("SendTransaction", ctx, tx)
}

// TransactionReceipt expectation helper
func (e *MockEVMClientExpectations) TransactionReceipt(ctx interface{}, txHash interface{}) *mock.Call {
	return e.mock.On("TransactionReceipt", ctx, txHash)
}

// ChainID expectation helper
func (e *MockEVMClientExpectations) ChainID(ctx interface{}) *mock.Call {
	return e.mock.On("ChainID", ctx)
}

// BlockNumber expectation helper
func (e *MockEVMClientExpectations) BlockNumber(ctx interface{}) *mock.Call {
	return e.mock.On("BlockNumber", ctx)
}

// PendingNonceAt expectation helper
func (e *MockEVMClientExpectations) PendingNonceAt(ctx interface{}, account interface{}) *mock.Call {
	return e.mock.On("PendingNonceAt", ctx, account)
}

// EstimateGas expectation helper
func (e *MockEVMClientExpectations) EstimateGas(ctx interface{}, call interface{}) *mock.Call {
	return e.mock.On("EstimateGas", ctx, call)
}

// SuggestGasPrice expectation helper
func (e *MockEVMClientExpectations) SuggestGasPrice(ctx interface{}) *mock.Call {
	return e.mock.On("SuggestGasPrice", ctx)
}

// Close expectation helper
func (e *MockEVMClientExpectations) Close() *mock.Call {
	return e.mock.On("Close")
}
